### ISSUE TITLE
Error at first run on Windows

### ISSUE THREAD

**Issue by ochronus** [ecoron/SerpScrap#28]
Windows 10, 64bit

scrape.py is a copy-paste of this: https://github.com/ecoron/SerpScrap/blob/master/examples/example_simple.py

-----

```
2018-01-06 07:46:11,421 - root - INFO - preparing phantomjs
2018-01-06 07:46:11,421 - root - INFO - detecting phantomjs
2018-01-06 07:46:11,424 - root - INFO - downloading phantomjs
Traceback (most recent call last):
  File ".\scrape.py", line 11, in <module>
    scrap.init(config=config.get(), keywords=keywords)
  File "C:\Users\Csaba Okrona\Devel\Own\serp-scraping\venv\lib\site-packages\serpscrap\serpscrap.py", line 84, in init
    firstrun.download()
  File "C:\Users\Csaba Okrona\Devel\Own\serp-scraping\venv\lib\site-packages\serpscrap\phantom_install.py", line 69, in download
    urllib.request.urlretrieve(base_url + file_name, '/tmp/' + file_name)
  File "c:\users\csaba okrona\appdata\local\programs\python\python36-32\Lib\urllib\request.py", line 258, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/phantomjs-2.1.1-windows.zip'
`

**Comment by ecoron** [comment]
Hi, thx for reporting.
Maybe the tmp folder doesn't exist or has no write permissions.
But I'll check if there is a better way to display the errormessage.

**Comment by ochronus** [comment]
Hi, yup that's definitely the reason but on windows it'll never automatically exist. I suggest using the tempfile module instead, as it's a cross-platform standard solution: https://docs.python.org/3/library/tempfile.html
